Fork /set.id/ syscalls for Go 1.4 support
https://code.google.com/p/go/source/detail?r=ae0d51eadf44 broke support for the
syscall.Setuid and syscall.Setgid functions that this package relies on.

Go 1.4 before this change:

    > sudo ./privsep.test -test.v
    === RUN TestPrivsep
    --- FAIL: TestPrivsep (120.01s)
        privsep_test.go:60: expected "pong\n", got "operation not supported\n"
        privsep_test.go:69: expected "foo\n", got ""
        privsep_test.go:82: child exited with status 2
    FAIL

After this change:

    > sudo ./privsep.test -test.v
    === RUN TestPrivsep
    --- PASS: TestPrivsep (0.00s)
        privsep_test.go:58: got expected reply "pong\n"
        privsep_test.go:67: got expected reply "foo\n"
        privsep_test.go:82: child exited with status -1
    PASS

Untested with respect to darwin support.